# Generated by Django 5.1.2 on 2024-11-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_comment_member_id_comment_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.CharField(default='10000', max_length=20, verbose_name='harga'),
        ),
    ]
